baseURL = "https://asia-2026.github.io/constitution-research/"
languageCode = "en-us"
title = "Living Constitution Research"
theme = "book"



[params]
  BookSection = "commentary"
  BookSearch = true
  BookToC = true
  BookLogo = "images/logo.png"
 

[[menu.main]]
  name = "Commentary"
  url = "/commentary/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2