baseURL = "https://asia-2026.github.io/constitution-research/"
languageCode = "en-us"
title = "Living Constitution Research"
theme = "book"

[params]
  BookSection = "all-posts"   # ⭐ ye change karo
  BookSearch = true
  BookToC = false
  BookLogo = "/constitution-research/images/logo.png"

[[menu.main]]
  name = "All Posts"
  url = "/all-posts/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2